name: bitway
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.4.0
  hangul: ^0.7.0
  shared_preferences: ^2.2.3  # 로컬 저장소를 위한 shared_preferences
  go_router: ^12.1.0  # 라우팅을 위한 go_router // 버전높일시 willScope 안먹힘
  dio: ^5.4.3               # HTTP 요청을 위한 Dio
  freezed_annotation: ^2.4.4  # 불변 모델 생성을 위한 Freezed
  json_annotation: ^4.9.0   # JSON 파싱을 위한 json_annotation
  riverpod_annotation: ^2.3.5  # 상태 관리를 위한 Riverpod
  hooks_riverpod: ^2.5.1     # Hook을 사용하기 위한 hooks_riverpod
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0  # 최신 버전 확인 후 수정
  firebase_auth: ^5.5.1 # Firebase 인증을 위한 firebase_auth
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  firebase_remote_config: ^5.4.1
  cached_network_image: ^3.4.1  # 이미지 캐싱을 위한 cached_network_image
  velocity_x: ^4.1.0  # UI를 위한 velocity_x
  eva_icons_flutter: ^3.1.0 # 아이콘을 위한 eva_icons_flutter
  google_fonts: ^6.2.1  # 구글 폰트를 위한 google_fonts
  flutter_cache_manager: ^3.3.0 # 캐시 관리를 위한 flutter_cache_manager
  envied: ^0.5.4+1  # 환경 변수를 위한 envied
  logger: ^2.4.0  # 로그를 위한 logger
  device_info_plus: ^11.4.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1 # 앱 아이콘을 위한 flutter_launcher_icons
  build_runner: ^2.4.12  # 빌드를 위한 build_runner
  riverpod_generator: ^2.4.0 # 상태 관리를 위한 riverpod_generator
  freezed: ^2.5.7 # 불변 모델 생성을 위한 freezed
  json_serializable: ^6.8.0  # JSON 파싱을 위한 json_serializable
  envied_generator: ^0.5.4+1  # 환경 변수를 위한 envied_generator
  url_launcher: ^6.3.0
  analyzer: ^6.7.0
  flutter_screenutil: ^5.9.3
  dropdown_button2: ^2.3.9
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/icon/bw_logo.png"
  image_path_android: "assets/images/icon/bw_logo.png"
  adaptive_icon_background: "assets/images/icon/main_bg.png"
  adaptive_icon_foreground: "assets/images/icon/bw_logo.png"
#  remove_alpha_ios: true



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/icon/